### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by pwFoo** [jejem/simple-orm#1]
Hi, nice simple examples like
```
//Load User with ID 1
$user = User::load(1);
```

But what's about other and more complex examples? For example load by fieldName?
Optional and not really needed: relation handling? load related data like post authors?

**Comment by jejem** [comment]
The goal of this simple ORM isn't to provide all the advanced features like Doctrine and Eloquent do, but merely to be able to load database rows and transform them in a PHP object/array, based on their primary key, with easy calls to CRUD methods.

There is no plans (at least for now) to add advanced features, as full ORMs have much bigger communities/support, and would be recommended for more advanced cases.
